#!/usr/bin/env python3
"""
05_validate_against_encode.py

APOL1 paper, step 5: independent validation.

THE PROBLEM WITH EVERYTHING SO FAR. Steps 2 to 4 rank variants by what a model
PREDICTS. Nothing yet tests those predictions against anything measured. A model
that confidently predicts nonsense would look identical at this stage.

THE TEST. ENCODE holds 85 DNase-seq peak files from human kidney. Those are
measured accessible regions, generated by other people, with no involvement of
the model. If the model's top-ranked variants are real regulatory candidates,
they should fall inside measured kidney DNase peaks more often than chance.

This is a genuine test with a real chance of failing, which is the point.

    H0  top-ranked variants are no more likely to sit in measured kidney
        accessible chromatin than the rest of the common variants at this locus
    H1  they are enriched

Enrichment is measured as an odds ratio with a Fisher exact test, comparing the
top N variants by predicted podocyte accessibility effect against all others in
the scored set. The background is deliberately the OTHER COMMON VARIANTS AT THE
SAME LOCUS, not the genome: every variant here already shares the locus's
sequence composition, gene density and mappability, so the comparison isolates
the ranking rather than rediscovering that APOL1 is in open chromatin.

A NULL RESULT IS REPORTABLE AND WOULD MATTER. If the top-ranked variants are not
enriched, the honest conclusion is that the model's accessibility channel does
not nominate real regulatory positions at this locus, and the paper says so.

Output: results/encode_validation.json

Author: Christopher Lawrence
"""

from __future__ import annotations

import glob
import gzip
import io
import json
import urllib.request
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
RESULTS = ROOT / "results"
PEAKS = DATA / "encode_peaks"
PEAKS.mkdir(parents=True, exist_ok=True)

CHROM = "chr22"
LOCUS_START, LOCUS_END = 36_140_330, 36_388_018
PODO = "dnase_glomerular_visceral_epithelial_cell"
ATAC = "atac_kidney"

ENCODE_SEARCH = (
    "https://www.encodeproject.org/search/?type=File&file_format=bed"
    "&output_type=peaks&assay_title=DNase-seq"
    "&biosample_ontology.term_name=kidney&assembly=GRCh38&status=released"
    "&limit=12&format=json&field=accession&field=href"
)
UA = {"User-Agent": "apol1-research/1.0", "Accept": "application/json"}


def fetch_peak_files(n: int = 8) -> list[Path]:
    idx = DATA / "encode_peak_index.json"
    if idx.exists():
        graph = json.loads(idx.read_text())
    else:
        req = urllib.request.Request(ENCODE_SEARCH, headers=UA)
        with urllib.request.urlopen(req, timeout=180) as fh:
            graph = json.load(fh)["@graph"]
        idx.write_text(json.dumps(graph))

    out = []
    for f in graph[:n]:
        acc = f["accession"]
        dest = PEAKS / f"{acc}.bed.gz"
        if not dest.exists():
            url = "https://www.encodeproject.org" + f["href"]
            print(f"  downloading {acc} ...")
            req = urllib.request.Request(url, headers={"User-Agent": UA["User-Agent"]})
            with urllib.request.urlopen(req, timeout=600) as r:
                dest.write_bytes(r.read())
        out.append(dest)
    return out


def load_locus_peaks(files: list[Path]) -> pd.DataFrame:
    """Peaks overlapping the APOL1 locus, from all files, with support count."""
    rows = []
    for f in files:
        with gzip.open(f, "rt") as fh:
            for line in fh:
                p = line.split("\t")
                if p[0] != CHROM:
                    continue
                s, e = int(p[1]), int(p[2])
                if e < LOCUS_START or s > LOCUS_END:
                    continue
                rows.append({"start": s, "end": e, "file": f.stem})
    return pd.DataFrame(rows)


def merge_intervals(df: pd.DataFrame, min_support: int) -> list[tuple[int, int]]:
    """Positions covered by at least `min_support` independent experiments."""
    if df.empty:
        return []
    events = []
    for _, r in df.iterrows():
        events.append((r["start"], 1))
        events.append((r["end"], -1))
    events.sort()
    out, depth, run_start = [], 0, None
    for pos, delta in events:
        prev = depth
        depth += delta
        if prev < min_support <= depth:
            run_start = pos
        elif prev >= min_support > depth and run_start is not None:
            out.append((run_start, pos))
            run_start = None
    return out


def in_any(pos: int, ivs: list[tuple[int, int]]) -> bool:
    for s, e in ivs:
        if s <= pos <= e:
            return True
        if s > pos:
            break
    return False


def main() -> None:
    print("fetching ENCODE kidney DNase peak files")
    files = fetch_peak_files()
    print(f"  {len(files)} files\n")

    raw = load_locus_peaks(files)
    print(f"peaks overlapping the locus: {len(raw):,} "
          f"from {raw['file'].nunique()} experiments")

    d = pd.concat([pd.read_csv(f, sep="\t")
                   for f in sorted(glob.glob(str(RESULTS / "scored" / "*.tsv.gz")))],
                  ignore_index=True).drop_duplicates(subset=["variant_id"])
    print(f"scored variants: {len(d):,}\n")

    out: dict = {"scored_variants": int(len(d)),
                 "peak_files": int(raw["file"].nunique())}

    for min_support in (1, 3):
        ivs = merge_intervals(raw, min_support)
        bp = sum(e - s for s, e in ivs)
        frac = bp / (LOCUS_END - LOCUS_START)
        d[f"in_peak_{min_support}"] = d["pos"].map(lambda p: in_any(p, ivs))
        base = float(d[f"in_peak_{min_support}"].mean())
        print("=" * 72)
        print(f"CONSENSUS PEAKS, support >= {min_support} experiments")
        print("=" * 72)
        print(f"  regions {len(ivs):,}, covering {bp:,} bp "
              f"({100*frac:.1f}% of the locus)")
        print(f"  variants inside a peak: {d[f'in_peak_{min_support}'].sum():,} "
              f"({100*base:.1f}%)")

        res = {}
        for col, lab in ((PODO, "podocyte DNase"), (ATAC, "kidney ATAC")):
            if col not in d.columns:
                continue
            s = d[d[col].notna()].copy()
            s["absv"] = s[col].abs()
            print(f"\n  ranked by |{lab}| prediction:")
            for topn in (25, 50, 100, 200):
                if topn >= len(s):
                    continue
                s2 = s.nlargest(topn, "absv")
                rest = s.drop(s2.index)
                a = int(s2[f"in_peak_{min_support}"].sum())
                b = topn - a
                c = int(rest[f"in_peak_{min_support}"].sum())
                dd = len(rest) - c
                orr, p = stats.fisher_exact([[a, b], [c, dd]])
                flag = ""
                if p < 0.05:
                    flag = "  *" if orr > 1 else "  * (DEPLETED)"
                print(f"    top {topn:>3}: {a:>3}/{topn} in peak "
                      f"({100*a/topn:>5.1f}%)  vs {100*c/len(rest):>5.1f}% "
                      f"background  OR {orr:>5.2f}  p {p:.3f}{flag}")
                res[f"{col}_top{topn}"] = {
                    "in_peak": a, "n": topn,
                    "pct": round(100 * a / topn, 1),
                    "background_pct": round(100 * c / len(rest), 1),
                    "odds_ratio": None if not np.isfinite(orr) else round(float(orr), 3),
                    "p": float(p)}
        out[f"support_{min_support}"] = {
            "regions": len(ivs), "bp": bp,
            "locus_fraction": round(frac, 4),
            "baseline_variant_pct": round(100 * base, 1),
            "tests": res}
        print()

    (RESULTS / "encode_validation.json").write_text(json.dumps(out, indent=2))
    print("=" * 72)
    print("READING THE RESULT")
    print("=" * 72)
    print("  OR > 1 with p < 0.05 means the model's top-ranked variants sit in")
    print("  MEASURED kidney accessible chromatin more often than the other")
    print("  common variants at this locus. That is independent support.")
    print("  OR near 1, or p not significant, means the ranking is not picking")
    print("  out real regulatory positions here, and the paper must say so.")
    print()
    print(f"  Wrote {RESULTS}/encode_validation.json")


if __name__ == "__main__":
    main()
